### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Korristo** [palfibeni/KerAzsMB#2]
Hello! After setting everything up according to guide, addon gives some errors (see attached) and cant create macros properly. What i already tryed:

1. Deleted all other addons and wtf folder, then repeated with only KerAzsMB
2. Moved scripts out of addon folder to interface folder
![Screenshot_1](https://user-images.githubusercontent.com/26342889/177050211-0c27c992-1874-47a0-9964-14b2d322b397.png)
[data.zip](https://github.com/palfibeni/KerAzsMB/files/9035201/data.zip)
)

**Comment by palfibeni** [comment]
Ah yes sorry this error shows, when you don't have [Supermacro ](https://legacy-wow.com/vanilla-addons/supermacro/)installed, which is you are correct not stated anywhere :/
I will update the readme, thanks for noticing!

**Comment by Korristo** [comment]
> Ah yes sorry this error shows, when you don't have [Supermacro ](https://legacy-wow.com/vanilla-addons/supermacro/)installed, which is you are correct not stated anywhere :/ I will update the readme, thanks for noticing!

installed supermacro. It solved the error problem. Following macros were generated in "specific macro" tab:

1. attack cross
2. attack skull
3. Buff
4. Follow
5. Mount Up
The problem is, when i press buttons with those macros - nothing happens (on warrior), Druid seems like working as intended (although uses only healing touch to heal, and healing himself, rather then warrior, also- buffs only self). tryed deleting wtf and wdb folders, didnt help. Also, as before tryed it with only 2 addons- KerAzsMB and supermacro- also no luck....
Seems like i'm missing some thing, attaching data.lua, didnt change anything else
[data.zip](https://github.com/palfibeni/KerAzsMB/files/9035680/data.zip)
.

**Comment by palfibeni** [comment]
Okay more note for myself:
Interface options / auto self cast should be DISABLED
About why the characters are not doing anything thats really interesting, I could only thing of that there is no skull or X raidTargetIcon placed? 
If you wish to function without always setting skull on targets, then you need to change the first line of the data.lua to:
`azs.targetingMode = "assist"`
